### ISSUE TITLE
Improve CSS UMA Module Testing

### ISSUE THREAD

**Issue by laurensdeb** [laurensdeb/authorization-agent#12]
Currently unit testing is missing from our custom CSS modules for UMA.

## Tasks
- [ ] Add unit testing
- [ ] Verify code coverage
- [ ] Add check to CI Pipeline
