### ISSUE TITLE
Pseudo-ACL: Viability and Proof-of-Concept

### ISSUE THREAD

**Issue by laurensdeb** [laurensdeb/authorization-agent#14]
The idea behind Pseudo-ACL's is to have the Authorization Service provide old-school Solid Applications with the ACL-format they know and trust while preventing these applications from overruling decisions made by the Authorization Agent.

## Requirements
- Pseudo-ACL's should be evaluated by the Authorization Service with a lower priority then the authorization decisions made by the authorization agent in its Registry Set.
- Pseudo-ACL's should reflect authorization decisions made by the registry set, as read-only triples. I.e. when making a request to the ACL auxiliary resource the Authorization Agent should determine what Shape Tree it belongs to and which agents or applications are authorized to access it this way triples can be generated conforming to the ACP/WAC specifications. **Note that this last part is important if a user chooses to migrate their Pod without awareness of Solid Interoperability specification**
- Pseudo-ACL's should allow old-style Solid applications to (1) interpret ACL rules and (2) add ACL triples for Agents and Applications that are not managed by the Registry Set.

## Tasks
- [ ] Define an interface for Pseudo-ACL modeling
- [ ] Define an interface for Pseudo-ACL serialization
- [ ] Define a data model for Pseudo-ACL's
- [ ] Prototype this using the InteropAuthorizer and ACP specification.
- [ ] Add a PseudoACL Authorizer which can authorize requests using the triples added by the client and add this as a lower priority option of authorization.

**Comment by laurensdeb** [comment]
Paused for now as our modules allow for the use of both WebACL and UMA as authorization mechanisms simultaneously.
