### ISSUE TITLE
Access Management Application: Prototype

### ISSUE THREAD

**Issue by laurensdeb** [laurensdeb/authorization-agent#17]
As discussed in our original paper on the topic, the use of the Access Management Application adds a new dimension to the interoperability specification. Once we are able to authorize requests based on the Interoperability specification (#15) we should look into how our Authorization Agent could be controlled by the Data Processing Grants served by the Access Management Application. 

## Tasks
- [ ] Add a prototype access management application for the Medical Records (and/or Income) case, use the Vue boilerplate we defined earlier on for this purpose.
- [ ] Define the API of a Data Processing Grant and document this properly in the thesis body and/or documentation pages of this repository.
- [ ] Add issuance of attestations to the Access Management Application backend.
- [ ] Implement an interface in the Authorization Agent for retrieving Access Needs from an application as well as a Data Processing Grant
- [ ] Implement the matching process between Access Need and Data Processing Grant
- [ ] Materialize the Access Grant in the user's Pod
